name: 'blender portable'
description: 'install portable blender from repo'
runs:
  using: 'composite'
  steps:
    - name: 'cache blender.zip'
      uses: actions/cache@v3
      id: cache-blender
      with:
        path: "$env:GITHUB_ACTION_PATH/blender.zip"
        key: ${{ runner.os }}-build-${{ env.cache-name }}

    - name: 'download portable'
      if: ${{ steps.cache-blender.outputs.cache-hit != 'false' }}
      shell: 'pwsh'
      run: |
        $uri = "https://mirrors.dotsrc.org/blender/release/Blender3.3/blender-3.3.1-windows-x64.zip"
        Invoke-WebRequest -Uri $uri -OutFile "$env:GITHUB_ACTION_PATH/blender.zip"

    - name: 'install blender'
      shell: 'pwsh'
      run: |
        cd "$env:GITHUB_ACTION_PATH"
        Write-Host CWD: (Get-Location)
        # Install-Module -Name SysAdminsFriends -Force
        # dir *.zip | Join-File "$env:GITHUB_ACTION_PATH/blender.zip"
        Expand-Archive -Path "$env:GITHUB_ACTION_PATH/blender.zip" -Force -DestinationPath "$env:GITHUB_ACTION_PATH"
        rm *.zip
        $folder=Get-ChildItem -Filter blender-* | Select -Expand Name
        cd "$env:GITHUB_ACTION_PATH/$folder"
        Write-Host BLENDER_ROOT: (Get-Location)
        echo "BLENDER_ROOT=$(Get-Location)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append